### PR TITLE
fix messages to preserve white space and wrap long urls

### PR DESCRIPTION
**Pull request by bryanbraun**
Fixes:
- preserves whitespaces and newlines
- wraps long urls

whitespace fixes

I was going to address the centered text issue, but I saw that it was already fixed in https://github.com/opsdroid/opsdroid-desktop/pull/13.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Many thanks for this. I should get a chance to review it tomorrow!

We're changing opsdroid from the GPLv3 to the Apache 2.0 license next week.
This doesn't affect your PR, but you should be made aware that your
contributions will be covered by the Apache 2.0 license 😊. For more info
see opsdroid/opsdroid#286.

**Review by jacobtomlinson — APPROVED** [review]
What an awesome fix! Way more minimal than I would've thought.

Happy to merge. Can you just respond saying you're happy with the license before I do?

**Comment by bryanbraun** [comment]
Sure thing! I feel fine about the license change. 👍

**Comment by jacobtomlinson** [comment]
Thanks!

**Pull request merged**
